name: orientation_guard
description: A robust orientation management package for Flutter that simplifies forcing and guarding screen orientation across Mobile and Web.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
