include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - require_trailing_commas
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - prefer_final_locals
    - sort_constructors_first
    - unawaited_futures

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
