// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_User _$UserFromJson(Map<String, dynamic> json) => _User(
  uid: json['uid'] as String,
  username: json['username'] as String,
  displayName: json['displayName'] as String,
  custLogin: json['custLogin'] as String,
  custId: json['custId'] as String,
  balance: (json['balance'] as num).toDouble(),
  avatarUrl: json['avatarUrl'] as String,
  brand: json['brand'] as String,
  currency: json['currency'] as String? ?? 'VND',
  gender: (json['gender'] as num?)?.toInt() ?? 0,
  email: json['email'] as String?,
  phone: json['phone'] as String?,
  status: json['status'] as String? ?? 'Active',
  isBanned: json['isBanned'] as bool? ?? false,
  isActivated: json['isActivated'] as bool? ?? false,
  isPhoneVerified: json['isPhoneVerified'] as bool? ?? false,
  isVerifiedBankAccount: json['isVerifiedBankAccount'] as bool? ?? false,
  platformId: (json['platformId'] as num?)?.toInt() ?? 0,
  customerId: (json['customerId'] as num?)?.toInt() ?? 0,
  isBot: json['isBot'] as bool? ?? false,
  isLockChat: json['isLockChat'] as bool? ?? false,
  isMute: json['isMute'] as bool? ?? false,
  canViewStat: json['canViewStat'] as bool? ?? false,
  isMerchant: json['isMerchant'] as bool? ?? false,
  playEventLobby: json['playEventLobby'] as bool? ?? false,
  lockGames: json['lockGames'] as List<dynamic>? ?? const [],
  affId: json['affId'] as String?,
  ipAddress: json['ipAddress'] as String?,
  timestamp: (json['timestamp'] as num?)?.toInt(),
  regTime: (json['regTime'] as num?)?.toInt(),
);

Map<String, dynamic> _$UserToJson(_User instance) => <String, dynamic>{
  'uid': instance.uid,
  'username': instance.username,
  'displayName': instance.displayName,
  'custLogin': instance.custLogin,
  'custId': instance.custId,
  'balance': instance.balance,
  'avatarUrl': instance.avatarUrl,
  'brand': instance.brand,
  'currency': instance.currency,
  'gender': instance.gender,
  'email': instance.email,
  'phone': instance.phone,
  'status': instance.status,
  'isBanned': instance.isBanned,
  'isActivated': instance.isActivated,
  'isPhoneVerified': instance.isPhoneVerified,
  'isVerifiedBankAccount': instance.isVerifiedBankAccount,
  'platformId': instance.platformId,
  'customerId': instance.customerId,
  'isBot': instance.isBot,
  'isLockChat': instance.isLockChat,
  'isMute': instance.isMute,
  'canViewStat': instance.canViewStat,
  'isMerchant': instance.isMerchant,
  'playEventLobby': instance.playEventLobby,
  'lockGames': instance.lockGames,
  'affId': instance.affId,
  'ipAddress': instance.ipAddress,
  'timestamp': instance.timestamp,
  'regTime': instance.regTime,
};
