part of 'caxilo_config_presets.dart';

// ==========================================
// GAME IN-HOUSE (SUNWIN)
// ==========================================
const _sharedInHouse = {
  "catalog": [
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_AVENGER",
      "game_code": "AVENGER",
      "game_name": "Avenger",
      "image": "sunwin_AVENGER_avenger_thumb.webp",
      "lang": "vi",
      "game_type": "slot",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "avenger_base_url",
      "launch_strategy": "standard",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_PIRATES",
      "game_code": "PIRATES",
      "game_name": "Hải Tặc",
      "image": "sunwin_PIRATES_haitac_thumb.webp",
      "lang": "vi",
      "game_type": "slot",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "pirates_base_url",
      "launch_strategy": "standard",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_SC",
      "game_code": "SC",
      "game_name": "Sun cá",
      "image": "sunwin_SC_sun-ca_thumb.webp",
      "lang": "vi",
      "game_type": "fish",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "fish88_base_url",
      "launch_strategy": "fish",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_AQUARIUM",
      "game_code": "AQUARIUM",
      "game_name": "Thủy Cung",
      "image": "sunwin_AQUARIUM_thuy-cung_thumb.webp",
      "lang": "vi",
      "game_type": "slot",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "aquarium_base_url",
      "launch_strategy": "standard",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_THAN_TAI",
      "game_code": "THAN_TAI",
      "game_name": "Thần Tài",
      "image": "sunwin_THAN_TAI_than-tai_thumb.webp",
      "lang": "vi",
      "game_type": "slot",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "thantai_base_url",
      "launch_strategy": "standard",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_SP",
      "game_code": "SP",
      "game_name": "Sun phụng",
      "image": "sunwin_SP_sun-phung_thumb.webp",
      "lang": "vi",
      "game_type": "miniGame",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_VT",
      "game_code": "VT",
      "game_name": "Volta",
      "image": "sunwin_VT_volta_thumb.webp",
      "lang": "vi",
      "game_type": "miniGame",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_VTS",
      "game_code": "VTS",
      "game_name": "Volta S",
      "image": "sunwin_VTS_volta-s_thumb.webp",
      "lang": "vi",
      "game_type": "miniGame",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_SR",
      "game_code": "SR",
      "game_name": "Sun rồng",
      "image": "sunwin_SR_sun-rong_thumb.webp",
      "lang": "vi",
      "game_type": "miniGame",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_SB88",
      "game_code": "SB88",
      "game_name": "Sicbo88",
      "image": "sunwin_SB88_sicbo88_thumb.webp",
      "lang": "vi",
      "game_type": "live",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_TX-LIVE",
      "game_code": "TX-LIVE",
      "game_name": "Tài Xỉu Live",
      "image": "sunwin_TX-LIVE_tai-xiu-live_thumb.webp",
      "lang": "vi",
      "game_type": "live",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_XD-LIVE",
      "game_code": "XD-LIVE",
      "game_name": "Xóc Đĩa Live",
      "image": "sunwin_XD-LIVE_xoc-dia-live_thumb.webp",
      "lang": "vi",
      "game_type": "live",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_BC-LT",
      "game_code": "BC-LT",
      "game_name": "Bầu Cua Lộc Thú",
      "image": "sunwin_BC-LT_bau-cua-loc-thu_thumb.webp",
      "lang": "vi",
      "game_type": "miniGame",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_LODE",
      "game_code": "LODE",
      "game_name": "Lô Đề",
      "image": "sunwin_LODE_lo-de_thumb.webp",
      "lang": "vi",
      "game_type": "lottery",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_XD-TL",
      "game_code": "XD-TL",
      "game_name": "Xóc Đĩa Tứ Linh",
      "image": "sunwin_XD-TL_xoc-dia-tu-linh_thumb.webp",
      "lang": "vi",
      "game_type": "miniGame",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_XD-TT-LIVE",
      "game_code": "XD-TT-LIVE",
      "game_name": "Xóc Đĩa Thủy Tinh Live",
      "image": "sunwin_XD-TT-LIVE_xoc-dia-thuy-tinh-live_thumb.webp",
      "lang": "vi",
      "game_type": "live",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_PKR-AOF",
      "game_code": "PKR-AOF",
      "game_name": "Poker All-in or Fold",
      "image": "sunwin_PKR-AOF_poker-all-in-or-fold_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "launch_strategy": "underDevelopment",
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_BINH-SUN",
      "game_code": "BINH-SUN",
      "game_name": "Mậu Binh",
      "image": "sunwin_BINH-SUN_mau-binh_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "table_games_base_url",
      "launch_strategy": "standard",
      "game_id": 4,
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_TIENLEN-SUN",
      "game_code": "TIENLEN-SUN",
      "game_name": "Tiến Lên",
      "image": "sunwin_TIENLEN-SUN_tien-len_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "table_games_base_url",
      "launch_strategy": "standard",
      "game_id": 1,
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_POKER-SUN",
      "game_code": "POKER-SUN",
      "game_name": "Poker",
      "image": "sunwin_POKER-SUN_poker_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "table_games_base_url",
      "launch_strategy": "standard",
      "game_id": 6,
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_LIENG-SUN",
      "game_code": "LIENG-SUN",
      "game_name": "Liêng",
      "image": "sunwin_LIENG-SUN_lieng_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "table_games_base_url",
      "launch_strategy": "standard",
      "game_id": 5,
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_SAM-SUN",
      "game_code": "SAM-SUN",
      "game_name": "Sâm Lốc",
      "image": "sunwin_SAM-SUN_sam-loc_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "table_games_base_url",
      "launch_strategy": "standard",
      "game_id": 2,
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_XOCDIA-SUN",
      "game_code": "XOCDIA-SUN",
      "game_name": "Xóc Đĩa",
      "image": "sunwin_XOCDIA-SUN_xoc-dia_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "table_games_base_url",
      "launch_strategy": "standard",
      "game_id": 9,
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_PHOM-SUN",
      "game_code": "PHOM-SUN",
      "game_name": "Phỏm",
      "image": "sunwin_PHOM-SUN_phom_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "table_games_base_url",
      "launch_strategy": "standard",
      "game_id": 8,
      "enable_host_message": true,
    },
    {
      "provider_id": "sunwin",
      "provider_name": "Sunwin",
      "product_id": "sunwin_BLACK_JACK-SUN",
      "game_code": "BLACK_JACK-SUN",
      "game_name": "Blackjack",
      "image": "sunwin_BLACK_JACK-SUN_blackjack_thumb.webp",
      "lang": "vi",
      "game_type": "card",
      "mobile_orientation": ["landscape"],
      "tablet_orientation": ["landscape"],
      "base_url_key": "table_games_base_url",
      "launch_strategy": "standard",
      "game_id": 13,
      "enable_host_message": true,
    },
  ],
  "visibility": {
    "AVENGER": {"is_visible": true, "status": "active"},
    "PIRATES": {"is_visible": true, "status": "active"},
    "SC": {"is_visible": true, "status": "active"},
    "AQUARIUM": {"is_visible": true, "status": "active"},
    "THAN_TAI": {"is_visible": true, "status": "active"},
    "SP": {"is_visible": true, "status": "under_development"},
    "VT": {"is_visible": true, "status": "under_development"},
    "VTS": {"is_visible": true, "status": "under_development"},
    "SR": {"is_visible": true, "status": "under_development"},
    "SB88": {"is_visible": true, "status": "under_development"},
    "TX-LIVE": {"is_visible": true, "status": "under_development"},
    "XD-LIVE": {"is_visible": true, "status": "under_development"},
    "BC-LT": {"is_visible": true, "status": "under_development"},
    "LODE": {"is_visible": true, "status": "under_development"},
    "XD-TL": {"is_visible": true, "status": "under_development"},
    "XD-TT-LIVE": {"is_visible": true, "status": "under_development"},
    "PKR-AOF": {"is_visible": true, "status": "under_development"},
    "BINH-SUN": {"is_visible": true, "status": "active"},
    "TIENLEN-SUN": {"is_visible": true, "status": "active"},
    "POKER-SUN": {"is_visible": false, "status": "active"},
    "LIENG-SUN": {"is_visible": true, "status": "active"},
    "SAM-SUN": {"is_visible": false, "status": "active"},
    "XOCDIA-SUN": {"is_visible": false, "status": "active"},
    "PHOM-SUN": {"is_visible": true, "status": "active"},
    "BLACK_JACK-SUN": {"is_visible": true, "status": "active"},
  },
};
